#!/bin/sh

for design in "bp-vram" "bs-vram"; do

  for uop in "rd" "wr" "blc" "wb" "wb_add" "wb_and" "wb_mask" "wb_mask_add" "wb_mask_and" "srl"; do

    if [ -f ${design}-${uop}.log ]; then
      str=$(tail -n1 ${design}-${uop}.log)

      if [ ! "${str}" == "OK" ]; then
        echo "* ${design}-${uop}:"
        tail -n15 ${design}-${uop}.log
      fi
    fi

  done

done
